mixed-port: 1089
allow-lan: true
mode: rule
ipv6: true
log-level: debug
external-controller: 127.0.0.1:9090
geodata-mode: true
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: false

hosts:
  'vultrsr.shupl.icu': 141.164.38.111
  'vultrsr2.shupl.icu': 158.247.233.24
  'vultrsr3.shupl.icu': 158.247.201.74

dns:
  enable: true
  ipv6: true

  proxy-server-nameserver:
    - 'quic://b.iqiq.io:784'
    - 'https://doh.pub/dns-query'

  default-nameserver:
    - 'https://1.12.12.12/dns-query'
    - 'https://223.5.5.5/dns-query'

  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - 'quic://b.iqiq.io:784'

  fallback:
    - 'https://dns.google/dns-query#代理'
    - 'https://1.1.1.1/dns-query#代理'

  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
      - greatfire


proxies:
  - name: Vultr 首尔 Xray
    type: vless
    server: vultrsr.shupl.icu
    port: 443
    uuid: CC332A95-3728-45FE-B136-83C3C0715F75
    network: tcp
    servername: vultrsr.shupl.icu
    flow: xtls-rprx-direct

  - name: Vultr 首尔 SS
    type: socks5
    server: 127.0.0.1
    port: 1091
    udp: true

  - name: Vultr 首尔2 Xray
    type: vless
    server: vultrsr2.shupl.icu
    port: 443
    uuid: CC332A95-3728-45FE-B136-83C3C0715F75
    network: tcp
    servername: vultrsr2.shupl.icu
    flow: xtls-rprx-direct

  - name: Vultr 首尔2 SS
    type: socks5
    server: 127.0.0.1
    port: 1092
    udp: true

  - name: Vultr 首尔3 Xray
    type: vless
    server: vultrsr3.shupl.icu
    port: 443
    uuid: CC332A95-3728-45FE-B136-83C3C0715F75
    network: tcp
    servername: vultrsr3.shupl.icu
    flow: xtls-rprx-direct

  - name: Vultr 首尔3 SS
    type: socks5
    server: 127.0.0.1
    port: 1093
    udp: true


proxy-groups:
  - name: 代理
    type: select
    proxies:
      - Vultr 首尔 SS
      - Vultr 首尔 Xray
      - Vultr 首尔2 SS
      - Vultr 首尔2 Xray
      - Vultr 首尔3 SS
      - Vultr 首尔3 Xray
      - 自动选择
      - 负载均衡

  - name: 自动选择
    type: url-test
    proxies:
      - Vultr 首尔 Xray
      - Vultr 首尔2 Xray
      - Vultr 首尔3 Xray
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 100

  - name: 负载均衡
    type: load-balance
    proxies:
      - Vultr 首尔 SS
      - Vultr 首尔2 SS
      - Vultr 首尔3 SS
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin

  - name: 苹果
    type: select
    proxies:
      - 代理
      - 直连

  - name: 微软
    type: select
    proxies:
      - 代理
      - 直连

  - name: Steam
    type: select
    proxies:
      - 代理
      - 直连

  - name: 直连
    type: select
    proxies:
      - DIRECT

  - name: 拦截
    type: select
    proxies:
      - REJECT

  - name: 未知
    type: select
    proxies:
      - 代理


rule-providers:

  Cloudflare:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare_Resolve.yaml"
    path: ./ruleset/Cloudflare.yaml
    interval: 10800

  Apple 1:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/UptonEdward/Rules/master/Apple.txt"
    path: ./ruleset/Apple 1.yaml
    interval: 10800

  Apple 2:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/Apple 2.yaml
    interval: 86400

  iCloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/iCloud.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/UptonEdward/Rules/master/Microsoft.txt"
    path: ./ruleset/Microsoft.yaml
    interval: 10800
  
  Wall:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/UptonEdward/Rules/master/Wall.txt"
    path: ./ruleset/Wall.yaml
    interval: 10800

  Direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/UptonEdward/Rules/master/Direct.txt"
    path: ./ruleset/Direct.yaml
    interval: 10800

  Steam:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/UptonEdward/Rules/master/Steam.txt"
    path: ./ruleset/Steam.yaml
    interval: 10800

  ChinaCIDR:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/UptonEdward/Rules/master/ChinaCIDR.txt"
    path: ./ruleset/ChinaCIDR.yaml
    interval: 10800

  Ads:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml"
    path: ./ruleset/Ads.yaml
    interval: 10800
  
  ChinaIPsBGP:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPsBGP/ChinaIPsBGP_IP.yaml"
    path: ./ruleset/ChinaIPsBGP.yaml
    interval: 10800

  ChinaIPs:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml"
    path: ./ruleset/ChinaIPs.yaml
    interval: 10800

  Proxy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical.yaml"
    path: ./ruleset/Proxy.yaml
    interval: 10800

rules:
  - RULE-SET,Ads,拦截
  - GEOSITE,category-ads-all,拦截
  - RULE-SET,Wall,代理
  - RULE-SET,Cloudflare,代理
  - RULE-SET,iCloud,苹果
  - RULE-SET,Apple 2,苹果
  - RULE-SET,Apple 1,苹果
  - RULE-SET,Microsoft,微软
  - RULE-SET,Steam,Steam
  - RULE-SET,Direct,直连
  - RULE-SET,Proxy,代理
  - RULE-SET,ChinaCIDR,直连
  - GEOIP,CN,直连
  - RULE-SET,ChinaIPs,直连
  - RULE-SET,ChinaIPsBGP,直连
  - NOT,((RULE-SET,ChinaCIDR)),代理

  - MATCH,未知