name: Generate ChinaCIDR RULE-SET
on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Generate ChinaCIDR.txt file
        run: |
          echo "payload:" > ChinaCIDR.txt
          curl -sSL http://ftp.apnic.net/stats/apnic/delegated-apnic-latest | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' > cidr4.txt
          sed -i -e 's/^/  - '\''/' cidr4.txt
          sed -i -e 's/$/'\''/' cidr4.txt
          curl -sSL http://ftp.apnic.net/stats/apnic/delegated-apnic-latest | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" 32-log($5)/log(2)}' > cidr6.txt
          sed -i -e 's/^/  - '\''/' cidr6.txt
          sed -i -e 's/$/'\''/' cidr6.txt
          cat cidr4.txt >> ChinaCIDR.txt
          cat cidr6.txt >> ChinaCIDR.txt

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          cp ChinaCIDR.txt ./publish/
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() && startsWith(github.ref, 'refs/tags/')}}
        with:
          tag: ${{ github.ref }}
          files: bin/*
          generate_release_notes: true
